# Generated by Django 6.0.4 on 2026-06-02 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_shopsaleitem_cost_price_per_unit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopSalePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("transfer", "Bank Transfer"),
                            ("pos", "POS"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Transfer reference or POS receipt number",
                        max_length=200,
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="core.shopsale",
                    ),
                ),
            ],
        ),
    ]
