# Generated by Django 6.0.4 on 2026-06-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_shopsalepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('egg', 'Egg'), ('drug', 'Drug / Supplement'), ('feed', 'Feed'), ('injection', 'Injection'), ('other', 'Other')], max_length=20, unique=True)),
                ('reorder_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='product_type',
            field=models.CharField(choices=[('egg', 'Egg'), ('drug', 'Drug / Supplement'), ('feed', 'Feed'), ('injection', 'Injection'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shopsale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('pos', 'POS')], default='cash', max_length=20),
        ),
    ]
