# Generated by Django 6.0.4 on 2026-06-18 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_producttypethreshold_alter_shopproduct_product_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agreed_price', models.DecimalField(decimal_places=2, help_text='Price per unit locked at order time', max_digits=10)),
                ('total_order_value', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('price_valid_until', models.DateField(blank=True, help_text='Leave blank for no expiry. After this date, price may be renegotiated.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('ready', 'Ready for Release'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', editable=False, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='core.shopproduct')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders_recorded', to='core.worker')),
                ('sale', models.OneToOneField(blank=True, help_text='Linked when goods are released', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_order', to='core.shopsale')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('pos', 'POS')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Transfer reference or POS receipt number', max_length=200)),
                ('payment_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits_recorded', to='core.worker')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='core.customerorder')),
            ],
        ),
    ]
