# Generated by Django 6.0.4 on 2026-06-18 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_customerorder_customerdeposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credit_balance', to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit Added'), ('applied', 'Applied to Order'), ('refunded', 'Refunded')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='core.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='core.customerorder')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions_recorded', to='core.worker')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('refund_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('pos', 'POS')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('authorised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds_authorised', to='core.worker')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='core.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='core.customerorder')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds_recorded', to='core.worker')),
            ],
        ),
    ]
