# Generated by Django 6.0.4 on 2026-06-19 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_customercreditbalance_customercredittransaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='sale',
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('ready', 'Ready for Release'), ('partially_released', 'Partially Released'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', editable=False, max_length=20),
        ),
        migrations.CreateModel(
            name='CustomerOrderRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposits_migrated', models.DecimalField(decimal_places=2, default=0, help_text='Amount of deposits applied to this sale', max_digits=12)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='core.customerorder')),
                ('released_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_releases', to='core.worker')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order_release', to='core.shopsale')),
            ],
        ),
    ]
