# Generated by Django 6.0.4 on 2026-06-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_customerorder_sale_alter_customerorder_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='agreed_price',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='total_order_value',
        ),
    ]
