# Generated by Django 6.0.4 on 2026-07-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_customerorder_agreed_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage for this product e.g. 5 for 5%', max_digits=5),
        ),
        migrations.AddField(
            model_name='shopsaleitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Computed discount amount — set automatically', max_digits=12),
        ),
        migrations.AddField(
            model_name='shopsaleitem',
            name='discount_applied',
            field=models.BooleanField(default=False, help_text='Whether discount was applied to this item'),
        ),
    ]
