# Generated by Django 6.0.4 on 2026-07-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_shopproduct_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Discount percentage for this product e.g. 5 for 5%', max_digits=8),
        ),
    ]
