# Generated by Django 6.0.4 on 2026-07-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_shopproduct_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='discount_fixed_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed discount amount per unit. Overrides percentage if set.', max_digits=10),
        ),
    ]
