# Generated by Django 6.0.4 on 2026-07-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_shopproduct_discount_fixed_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='discount_percentage',
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='discount_fixed_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed discount amount per unit e.g. ₦100 means ₦100 off per unit', max_digits=10),
        ),
    ]
