# Generated by Django 6.0.4 on 2026-07-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_shopproduct_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='egg_grade',
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='unit',
            field=models.CharField(choices=[('crate', 'Crate'), ('bag', 'Bag'), ('vial', 'Vial'), ('sachet', 'Sachet'), ('bottle', 'Bottle'), ('litre', 'Litre'), ('kg', 'Kg'), ('unit', 'Unit')], default='crate', max_length=50),
        ),
    ]
