# Generated by Django 6.0.4 on 2026-07-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_shopproduct_egg_grade_alter_shopproduct_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsaleitem',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
