# Generated by Django 6.0.4 on 2026-07-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_shopsaleitem_price_per_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopstock',
            name='reorder_threshold',
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='reorder_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum stock level before low stock alert triggers', max_digits=10),
        ),
    ]
