# Generated by Django 6.0.4 on 2026-07-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_shopstock_reorder_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='discount_applied',
            field=models.BooleanField(default=False, help_text='Whether discount is agreed for this order'),
        ),
    ]
